// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpQY4vFvsBfk4ifkcczRXC3Ng7FNWJlCM',
    appId: '1:247144870371:web:150f4431144f49ce8770d6',
    messagingSenderId: '247144870371',
    projectId: 'flutter-project-48be0',
    authDomain: 'flutter-project-48be0.firebaseapp.com',
    storageBucket: 'flutter-project-48be0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46jh1v8gPJwI2ngzIfBzL-nPSzhk0oKc',
    appId: '1:247144870371:android:250f643113af2c718770d6',
    messagingSenderId: '247144870371',
    projectId: 'flutter-project-48be0',
    storageBucket: 'flutter-project-48be0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoU5sJddN6BDyFmDx0SVjqFClHjmS0KmY',
    appId: '1:247144870371:ios:7362d5714c0149028770d6',
    messagingSenderId: '247144870371',
    projectId: 'flutter-project-48be0',
    storageBucket: 'flutter-project-48be0.appspot.com',
    iosBundleId: 'com.example.tpFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoU5sJddN6BDyFmDx0SVjqFClHjmS0KmY',
    appId: '1:247144870371:ios:1ef44462b85825878770d6',
    messagingSenderId: '247144870371',
    projectId: 'flutter-project-48be0',
    storageBucket: 'flutter-project-48be0.appspot.com',
    iosBundleId: 'com.example.tpFirebase.RunnerTests',
  );
}
